import pandas as pd

{% if AnalysisType == "single" %}
description = pd.read_csv('sample_description.csv').reset_index().to_dict("records")
{% endif %}

{% if AnalysisType == "single" and cell_ranger and not fq_dump and not bam and not panglao and db == 'GEO' %}
barcodes =  {x['run_accession']: x['fastq_ftp'].split(';')[0] for x in description}
{% elif AnalysisType == "single" and cell_ranger and not fq_dump and not bam and not panglao and db == 'MTAB' %}
barcodes =  {x['ena_run']: x['fastq_1'] for x in description}
{% elif AnalysisType == "single" and cell_ranger and not fq_dump and bam and not panglao %}
bam_files = {run['run_accession']: f"ftp://{run['submitted_ftp'].split(';')[0]}" for run in description}
{% elif AnalysisType == "single" and cell_ranger and fq_dump and not panglao %}
runs = [x['run_accession'] for x in description]
{% endif %}

{% if AnalysisType == "single" and not panglao %}
include: "rules/get_data.smk"
{% if cell_ranger and not panglao %}
include: "rules/define_version.smk"
{% endif %}
include: "rules/run_kallisto.smk"
include: "rules/get_counts.smk"
{% endif %}
include: "rules/secondary_analysis.smk"
include: "rules/add_uns.smk"

localrules: add_uns_to_h5ad

rule all:
    input: "{{ RunName }}_with_uns.h5ad"